### ISSUE TITLE
Error: Address already in use. When run a spring boot jar by different cmd prompt at the same time 

### ISSUE THREAD

**Issue by EddieCHUYICHENG** [EddieCHUYICHENG/Issues#2]
Run a jar without any parameters, the main process will start several threads. After that, if you try to run same jar again, the error message will be showed in the Cmd prompt.

RuntimeException message as below :
````
### ERROR(2018-05-23 14:00:48,724){main:DirectJDKLog.java:181}-Failed to start end point associated with ProtocolHandler [http-nio-8888]
java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_172]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:1.8.0_172]
        at sun.nio.ch.Net.bind(Unknown Source) ~[?:1.8.0_172]
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[?:1.8.0_172]
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[?:1.8.0_172]
        at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:980) ~[tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:573) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.connector.Connector.startInternal(Connector.java:993) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225) [tomcat-embed-core-8.5.11.jar!/:8.5.11]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:241) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:184) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545) [spring-context-4.3.6.RELEASE.jar!/:4.3.6.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:370) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-1.5.1.RELEASE.jar!/:1.5.1.RELEASE]
        at com.t1.smartbackend.Application.main(Application.java:22) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [smartbackend-game-engine.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [smartbackend-game-engine.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [smartbackend-game-engine.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [smartbackend-game-engine.jar:0.0.1-SNAPSHOT]
2018-05-23 14:00:48,741 main ERROR Unable to move file c:\Users\Eddie\Desktop\Work\test\game-log-sync-jar\.\logs\default\default_error.log to c:\Users\Eddie\Desktop\Work\test\game-log-sync-jar\.\logs\default\2018-05-23\default_error_2018-05-23-13.log: java.nio.file.FileSystemException c:\Users\Eddie\Desktop\Work\test\game-log-sync-jar\.\logs\default\default_error.log -> c:\Users\Eddie\Desktop\Work\test\game-log-sync-jar\.\logs\default\2018-05-23\default_error_2018-05-23-13.log: 程序無法存取檔案，因為檔案正由另一個程序使用。

2018-05-23 14:00:48,746 main ERROR Unable to delete file c:\Users\Eddie\Desktop\Work\test\game-log-sync-jar\.\logs\default\default_error.log: java.nio.file.FileSystemException c:\Users\Eddie\Desktop\Work\test\game-log-sync-jar\.\logs\default\default_error.log: 程序無法存取檔案，因為檔案正由另一個程序使用。
````

**Comment by EddieCHUYICHENG** [comment]
Solution : https://community.talend.com/t5/Migration-Configuration-and/quot-Address-already-in-use-quot-error-with-Spring-Boot-services/ta-p/25724

**Comment by EddieCHUYICHENG** [comment]
Replace instrument to --> java **-Dserver.port=8081** -jar smartbackend-game-engine.jar AginGameSyncBsm "2018-04-23 00:08:00" "2018-04-23 00:14:00" ""
